# Generated by Django 5.1.1 on 2024-09-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoAcidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100)),
                ('responsavel_setor', models.CharField(max_length=100)),
                ('descricao_atividade', models.TextField()),
                ('descricao_risco', models.TextField()),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('nome_colaborador', models.CharField(max_length=100)),
                ('sugestao_melhorias', models.TextField(blank=True, null=True)),
                ('parecer_seguranca', models.TextField(blank=True, null=True)),
                ('prazo_resolucao', models.CharField(blank=True, max_length=100, null=True)),
                ('risco_neutralizado', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('parcialmente', 'Parcialmente')], max_length=20)),
                ('metodo_neutralizacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
